import fs from 'fs';

const path = 'src/data/projects.js';
let content = fs.readFileSync(path, 'utf8');

const jsonMatch = content.match(/export const projects = (\[[\s\S]*\]);/);
if (jsonMatch) {
  let arr = JSON.parse(jsonMatch[1]);

  // Remove projects with no description or placeholder image
  arr = arr.filter(p => {
    const isNoDesc = !p.description || p.description.trim() === '' || p.description === 'No description available.';
    const isPlaceholderImg = !p.image || p.image === '/assets/placeholder-project.png';
    return !isNoDesc && !isPlaceholderImg;
  });

  // Reassign IDs
  arr.forEach((p, idx) => {
    p.id = idx;
  });

  const fileContent = `// This file is auto-generated by scripts/update-projects.js
// Do not edit directly. Update src/data/projects-config.json for custom metadata.

export const projects = ${JSON.stringify(arr, null, 2)};
`;

  fs.writeFileSync(path, fileContent);
  console.log(`Cleaned projects! ${arr.length} valid projects remaining.`);
}
