import fs from 'fs';

const path = 'src/data/projects.js';
let content = fs.readFileSync(path, 'utf8');
const jsonMatch = content.match(/export const projects = (\[[\s\S]*\]);/);
if (jsonMatch) {
  let arr = JSON.parse(jsonMatch[1]);
  arr = arr.filter(p => p.description && p.description.trim() !== '' && p.demo && p.demo.trim() !== '');
  arr.forEach((p, i) => p.id = i);
  const updatedStr = JSON.stringify(arr, null, 2);
  const fileOutput = `// This file is auto-generated by scripts/update-projects.js\n// Do not edit directly. Update src/data/projects-config.json for custom metadata.\n\nexport const projects = ${updatedStr};\n`;
  fs.writeFileSync(path, fileOutput);
  console.log('Cleaned projects.js count:', arr.length);
}
