import fs from 'fs';

const path = 'src/data/projects.js';
let content = fs.readFileSync(path, 'utf8');

const jsonMatch = content.match(/export const projects = (\[[\s\S]*\]);/);
if (jsonMatch) {
  let arr = JSON.parse(jsonMatch[1]);
  // Filter out any duplicate MS Ochieng Law that has 'No description available.'
  arr = arr.filter(p => !(p.title === 'MS Ochieng Law' && p.description === 'No description available.'));
  
  // Reassign IDs
  arr.forEach((p, idx) => {
    p.id = idx;
  });

  const fileContent = `// This file is auto-generated by scripts/update-projects.js
// Do not edit directly. Update src/data/projects-config.json for custom metadata.

export const projects = ${JSON.stringify(arr, null, 2)};
`;

  fs.writeFileSync(path, fileContent);
  console.log(`Successfully updated ${arr.length} projects in projects.js`);
}
